// Code generated by goctl. DO NOT EDIT.
// Source: add.proto

package addclient

import (
	"context"

	"github.com/neccohuang/grpc-add/add"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = add.Request
	Response = add.Response

	Add interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAdd struct {
		cli zrpc.Client
	}
)

func NewAdd(cli zrpc.Client) Add {
	return &defaultAdd{
		cli: cli,
	}
}

func (m *defaultAdd) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := add.NewAddClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
